server:
  # debug test release
  mode: debug
  port: 6001

oidc:
  id: "tamp-oidc"
  redirectUris:
    - http://tamp-test.yingmi.cn/api/v1/oidc/callback
  responseType:
    - code
  grantType:
    - authorization_code
  scope:
    - openid  
    - tamp
  public: true
  tokenUri: http://tamp-test.yingmi.cn/api/v1/oidc/token
  # authUri:  http://tamp-test.yingmi.cn/h5/tamp-auth
  authUri:  http://tamp-test.yingmi.cn/debug/tamp-auth
  secret: secret
  issuer: http://tamp-test.yingmi.cn

gateway:
  host: http://localhost:8001

tradeGateway:
  host: https://luna-tamp-test.yingmi.cn
  appID: oxG9SIXIfQImt2hJBaaT3WKFLdr7hXDS
  appSecret: secret

openTokenSecret: secret

wechatLoginURL: http://login-provider.adapter/api/v1/provider/login

chat:
  host: "http://localhost:8008"
  password: password

redis:
  addr: "localhost:6379"
  password: password
  db: 5

tokenExpires: 7200
refreshTokenExpires: 86400

mongo:
  addrs:
    - "localhost:3717"
  database: "uac"
  replicaSet: "mgset-30621929"
  source: admin
  username: root
  password: password

tampManagerHost: http://tamp-manager.swan:3000